### PR TITLE
Add Geomap example project

### PR DESCRIPTION
**Pull request by tdimnet**
Add GeoMap example project:
- init the `yarn create @datadog/app`
- Small typo fix in the doc
- Create a Datadog App (Geo Map) and a Dashboard (Geo Map App Dashboard) 
- Use template variables throughout the client SDK.

Architecture:
- API in Crystal
- Datadog App in React
- Bootstrapping scripts in NodeJS

TODO:
- Update Readme
- Clean Datadog App (remove useless side-panels, widgets and modals).
- Add error modal on error.

### CODE REVIEW

**Comment by MattMacD78** [comment]
proposed improvements here : https://github.com/DataDog/apps/pull/91

**Comment by joneshf-dd** [comment]
👋🏾 Not sure what the status is here, but if it's at all possible, can this hold off on merging until after https://github.com/DataDog/apps/pull/92 has merged? More than happy to help fix whatever needs to be fixed as a result.

**Comment by tdimnet** [comment]
@joneshf-dd : yes, of course, it can wait a few more days.
I'd like to clean up some part of the code and add documentation before I create the official PR.

Let me know when you have merged your PR. In the meantime, I'll look at it in order to keep track of the repo 😃

**Comment by joneshf-dd** [comment]
Okay. It's all merged in! I think for the most part it should be changes to the `package.json` files and maybe updating for formatting/linting stuff. Lemme know if you need any help with anything, either here or on Slack.

**Pull request merged**
