### PR TITLE
UIAPPS-141 Detangle module dependencies

### PR DESCRIPTION
**Pull request by joneshf-dd**
## Motivation

- Jira Issue: https://datadoghq.atlassian.net/browse/UIAPPS-141
- We want to break the dependency cycles we have between most of the modules in the SDK.

## Changes

- We define a bunch of interfaces and use them to write code against rather than having everything depend on `DDClient`.
- We also enable the `import/no-cycle` rule so we don't backslide.

| Before                         | After                        |
| ------------------------------ | ---------------------------- |
| modules with a bunch of dependency cycles | modules without any depednecy cycles |

Legend:
- Green - no dependencies
- Purple - has normal dependencies
- Red - has circular dependencies

## Releases

Choose one:

-   [ ] No release is necessary.
        If you're only updating examples/documentation, this is likely what you want.
-   [x] All packages that need a release have a changeset.

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @datadog/create-app@1.0.3-canary.98.c0e1e09.0
  npm install @datadog/framepost@0.3.1-canary.98.c0e1e09.0
  npm install @datadog/ui-extensions-sdk@0.25.1-canary.98.c0e1e09.0
  # or 
  yarn add @datadog/create-app@1.0.3-canary.98.c0e1e09.0
  yarn add @datadog/framepost@0.3.1-canary.98.c0e1e09.0
  yarn add @datadog/ui-extensions-sdk@0.25.1-canary.98.c0e1e09.0
  ```
</details>

### CODE REVIEW

**Review by nmuldavin — COMMENTED** [review]
I'm sorry for my late response on this one.

I have a (maybe) dumb question here: 

What's the difference between this change, in which we split the interface from the implementation, and what typescript does under the hood? To be honest i'm murky on what typescript actually does under the hood, but my working understanding is when you create a `class` it automatically creates both an interface and implementation, such that when you do `import type` you're actually importing the interface not the implementation.

**Comment by joneshf-dd** [comment]
No worries. I honestly had no idea how TS was handling this. That's interesting to learn!

From what you describe, it doesn't seem like there's really much difference. The two things that really pop up for me are:
1. This is explicit and forces us to break the cycle ourselves. I think this helps with the mental model of how everything fits together.
2. We're a bit more granular since nothing requires the full public interface of a `DDClient` anymore. I think this opens the door to future simplifications/improvements/easier testing, but that remains to be seen.

**Review by nmuldavin — APPROVED** [review]
Well justified, let's see how it goes! If it feels like too much of a maintenance burden, i think it will be possible to re-tangle at least in the short term before there's any divergence between interface and implementations

**Comment by joneshf-dd** [comment]
Thanks for the review!

**Pull request merged**
