### PR TITLE
Remove dynamic widgets

### PR DESCRIPTION
**Pull request by enbashi**
Remove the ability to define custom widgets by code: `client.dashboard.customWidget.onRequest`.

### CODE REVIEW

**Review by nmuldavin — APPROVED** [review]

**Comment by ytnytn1** [comment]
Hi, @enbashi. 
I use this ability in my integration. Was that constantly removed?

**Comment by enbashi** [comment]
> Hi, @enbashi.
> I use this ability in my integration. Was that permanently removed?

hey @ytnytn1, can you share more details your use case for this feature? What's the name of your integration? Are you a Datadog user? If so, what is your organization name?

**Comment by ytnytn1** [comment]
> > Hi, @enbashi.
> > I use this ability in my integration. Was that permanently removed?
> 
> hey @ytnytn1, can you share more details your use case for this feature? What's the name of your integration? Are you a Datadog user? If so, what is your organization name?

I'm from Shoreline. I'm developing Shoreline integration for Datadog. 

The use case is quite standard. I define a widget and some options but it was very convenient to define it through the code as I had full control over it. Now I have to update the app manifest if I need to add a new widget or change its options. Also, we have multiple testing environments and for each environment, we have a separate Datadog app. And it is very hard to update the manifest for each app manually when I need to make changes in widget definition. Definition through the code also allowed to escape this problem.

**Comment by enbashi** [comment]
Thanks for the details and I apologize for the inconvenience @ytnytn1. The feature was prone to errors and glitches because of its dynamic nature. For the time being, static definition is the only way to define widgets. I hope to come back to you with some workarounds in the near future, but not promises.

**Comment by ytnytn1** [comment]
> Thanks for the details and I apologize for the inconvenience @ytnytn1. The feature was prone to errors and glitches because of its dynamic nature. For the time being, static definition is the only way to define widgets. I hope to come back to you with some workarounds in the near future, but not promises.

Thank you for the explanation! I've already switched to static widgets declaration in the manifest file.

**Pull request merged**
