### PR TITLE
UIAPPS-69 Start on `npm init` package for creating a Datadog App

### PR DESCRIPTION
**Pull request by joneshf-dd**
## Motivation

- Jira Issue: https://datadoghq.atlassian.net/browse/UIAPPS-69
- This is a redo of: https://github.com/DataDog/apps-archive/pull/39. Requesting a review from Noah, since he already reviewed it there. Nothing really changed except some CI stuff and combining/shuffling the commits.

## Changes

There's two main things happening in this PR:

1. We're reverting https://github.com/DataDog/apps-archive/pull/29. We're doing this for two reasons: it'll be one less repo to maintain in the long run, it makes the rest of this PR easier.

1. We add a `@datadog/create-app` package. This uses the `starter-kit` to allow a workflow where people only need to type `yarn create @datadog/app` or `npm init @datadog/app` to get started.

## Testing

1. [ ] Run `yarn create @datadog/app --commit 221cec615c01596136007722b924f7956de8b9a1`.
    - Since the current `master` branch doesn't have the `starter-kit` we have to use a specific commit that does. Once merges, we can let the defaults take over and say `yarn create @datadog/app` to install the `starter-kit`
2. [ ] Should download the `starter-kit` example to the `starter-kit` directory and install dependencies (with `yarn`).

## Follow-up

- [ ] Remove the https://github.com/DataDog/starter-kit repo.

## Change Type

- [ ] `patch`
- [ ] `minor`
- [x] `major`

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @datadog/create-app@1.0.1-canary.70.a229f3c.0
  npm install @datadog/ui-extensions-sdk@0.24.3-canary.70.a229f3c.0
  # or 
  yarn add @datadog/create-app@1.0.1-canary.70.a229f3c.0
  yarn add @datadog/ui-extensions-sdk@0.24.3-canary.70.a229f3c.0
  ```
</details>

### CODE REVIEW

**Comment by joneshf-dd** [comment]
Just a note, this looks like it's going to publish the package at 1.0.1. Clearly I don't understand how `auto` decides which version to make. I thought it was looking at the "Change Type" in the description, but it doesn't seem like it. Might be missing a setup somewhere.

I'll dig into this a bit to see if we can't make it work right, but also it shouldn't be a huge deal to have a 1.0.1 version.

**Review by nmuldavin — APPROVED** [review]

**Comment by nmuldavin** [comment]
I don't particularly care what version the npm init package has but we do care about other packages (the sdk) where we want to make it really clear we're in pre-release

**Comment by joneshf-dd** [comment]
Yeah, it *should* not mess with the other packages. Far as I understand it, it'll only make releases for packages that have changes. So since we only changed things in `packages/create-app`, that's the only thing that will be released.

If I've totally misunderstood things and we do accidentally publish a 1.0.0 for the SDK, we should be able to run `npm unpublish` or `npm deprecate` to deal with it.

**Comment by joneshf-dd** [comment]
Since it looks like we're okay going with independent versions, and it looks like we're only going to get patch versions in the interim, I'm going to merge this so it's one less thing in flight.

Thanks for the review, again!

**Pull request merged**
